language: ruby
dist: trusty
services:
- docker
rvm:
- 2.4.0
branches:
  only:
  - production
  - staging
  - aws-deploy-setup
  - "/^greenkeeper\\/.*$/"
before_deploy:
- pip install --upgrade --user awscli
deploy:
- provider: script
  script: "./deploy/deploy.sh $STAGING_CLUSTER_STACK $STAGING_APP_STACK $STAGING_REPOSITORY_NAME $STAGING_DESIRED_COUNT"
  on:
    branch: develop
- provider: script
  script: "./deploy/deploy.sh $STAGING_CLUSTER_STACK $STAGING_APP_STACK $STAGING_REPOSITORY_NAME
    $STAGING_DESIRED_COUNT"
  on:
    branch: staging
- provider: script
  script: "./deploy/deploy.sh $PROD_CLUSTER_STACK $PROD_APP_STACK $PROD_REPOSITORY_NAME
    $PROD_DESIRED_COUNT"
  on:
    branch: production
notifications:
  slack:
    rooms:
      secure: 1CMBsemLsoz/bAUUM2aHDyRp+Jhx3TEWKLVIPZizeCIqRfzTb5bTIPAI2BEaaGtYnSWjcMnGJu9ejCvghhKZ+DFY2Yl7lClRDC+WIWPnWDEMt1T9cDLWrB2Cb+UcPVdEhkPNSJ9pKDHTs6GlyifJN5AMmGISbhp4uOJkxAYoQAt39vRgmJVod7Iprlwuy0ch9kkl8HJ36xaX4t7XNHMa57YaR+LD1gyPTYPti+6VHmh8MVu5GP5bt9VSJYA1EvtRvJnyiBA9lbgvn1dFE/AERRu2dWYUph7zW5bkrZpBKHXlQ5iHP3/oBL0DtqIxei2mGaCyFhGn+uto54l1Bi5zZ/r86j9k/C8oSwQL1YQ+QhmImMTZKRTWIZ4kfI3zZ7+1NyxgzCWpgD3MTQFTEdqxb+xmjuWJ9il88gXWk+PLuVEbGX6ucMDKKG4gV6OX8ofnCzAC7KH2vr3ialXj4DNBhsfTur6MBjWwOsBmWpJZ8QzZl3IESAVmHAv5sl6hdO1+PwewwFHiy3/nDmuFTZRiB0Mv+sa1o+j1YpaP0bBjhAbJdXsS9c/w4kgzMFMydGSIn0RRWSmnFPrTdc9f+q7mF8zvTXD9D/KsSn5JPCUnq3hB5BonPmDQHWantPSQAblppAfLSUlZYVLG3sjxKCaZQpdj9GENLNjqfPGm1BHmQsk=
